''' Even Fibonacci Numbers '''

''' Prompt ''' 
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...


''' Question ''' 
# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, find the sum of the even-valued terms.


def even_fibonacci_sum(first_term,second_term,last_term):
    next_term = 0
    running_sum = second_term
    while next_term < last_term:
        next_term = first_term + second_term
        if (next_term % 2) == 0:
            running_sum += next_term
        first_term = second_term
        second_term = next_term
    return running_sum

first_term, second_term, last_term = 1, 2, 4e6
even_fibonacci_sum(first_term,second_term,last_term)
# Output: 4613732           
        
